**1. Import the numpy package under the name np**

In [1]:
import numpy as np

**2. Print the numpy version and the configuration**

In [2]:
print(np.__version__)
print(np.show_config())

1.20.1
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/joshb/anaconda3/envs/Strive_AI\\Library\\lib']
    include_dirs = ['C:/Users/joshb/anaconda3/envs/Strive_AI\\Library\\include']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/joshb/anaconda3/envs/Strive_AI\\Library\\lib']
    include_dirs = ['C:/Users/joshb/anaconda3/envs/Strive_AI\\Library\\include']
    language = f77
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['C:/Users/joshb/anaconda3/envs/Strive_AI\\Library\\lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['C:/Users/joshb/anaconda3/envs/Strive_AI\\Library\\lib']
    langu

**3. Create a null vector of size 10**

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**4. How to find the memory size of any array**

In [12]:
arr = np.zeros(5)
memory = arr.size * arr.itemsize
memory

40

**5. How to get the documentation of the numpy add function from the command line?**

In [13]:
### May have understood question wrong, belive this is what the question asked

arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[1, 2, 3], [4, 5, 6]])

answer = arr_1 + arr_2
answer

array([[ 2,  4,  6],
       [ 8, 10, 12]])

**6. Create a null vector of size 10 but the fifth value which is 1**

In [15]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**7. Create a vector with values ranging from 10 to 49**

In [19]:
arr = np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**8. Reverse a vector (first element becomes last)**

In [23]:
### From bracket desciption I belive this is whats wanted, could be the case they want a complete reverse order?

arr = np.arange(1, 10)
arr[[-1, 0]] = arr[[0, -1]]
arr

array([9, 2, 3, 4, 5, 6, 7, 8, 1])

**9. Create a 3x3 matrix with values ranging from 0 to 8**

In [24]:
arr = np.matrix([[0, 1 , 2], [3, 4, 5], [6, 7, 8]])
arr

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

**10. Find indices of non-zero elements from [1,2,0,0,4,0]**

In [27]:
arr = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

**11. Create a 3x3 identity matrix**

In [28]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**12. Create a 3x3x3 array with random values**

In [29]:
### Think 3x3x3 means 3 seperate 3x3 arrays

arr = np.random.rand(3 , 3, 3)
arr

array([[[0.77255074, 0.76746067, 0.25072767],
        [0.58555042, 0.84508528, 0.58343692],
        [0.94944482, 0.8490138 , 0.33653484]],

       [[0.33029465, 0.87927174, 0.46667162],
        [0.58146911, 0.49806635, 0.36113418],
        [0.08860803, 0.88102457, 0.12330829]],

       [[0.5036147 , 0.69354951, 0.21782251],
        [0.06160713, 0.0643988 , 0.1000805 ],
        [0.58518376, 0.42265056, 0.64392538]]])

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [30]:
arr = np.random.normal(size=(10, 10))
arr

array([[ 1.50829888,  0.71025818, -1.18560863,  0.87826069,  0.01432555,
        -0.30629261, -0.89423402,  2.11001352, -2.48150445,  0.54001426],
       [ 0.97654609,  0.08306143, -1.10116087, -1.02194525,  1.88594427,
         0.07506107, -0.48935445,  1.3894233 , -1.27528495,  0.97587285],
       [ 0.47404926,  0.01931964,  0.31354789, -0.06826457, -0.46212089,
         1.44314113, -0.86670791, -2.00251037, -0.18374271,  1.00574827],
       [ 0.66850721,  1.13702733,  0.24866291, -0.13083156,  0.62902912,
        -0.26086427, -0.84185611,  1.16870932, -0.34975373, -0.82478872],
       [ 0.53550146,  0.22976803,  0.870866  ,  1.89015899, -1.25694942,
        -1.38734892, -1.08353104,  1.03600605,  1.19201069,  1.34036666],
       [-2.17576272,  0.56343541,  0.77369714, -0.07143058, -1.10435298,
        -0.34199844,  0.06841519, -0.33099792, -0.36071049, -0.09102912],
       [-0.33722133,  1.07113605,  0.5428004 ,  1.10711539, -1.52521911,
         0.17222086, -1.52190598,  2.85451331

In [31]:
np.min(arr), np.max(arr)

(-2.4815044545014833, 2.8545133141920873)

**14. Create a random vector of size 30 and find the mean value**

In [35]:
arr = np.random.normal(size=30)
arr

array([ 0.3420901 , -0.17449704,  0.11673486,  1.24369553,  2.17150927,
        1.57498062,  1.23115186,  1.65455254,  0.15764962,  0.63085381,
        1.8001015 ,  1.69305888, -0.23069221,  1.79247721, -0.12572021,
        0.83833115,  0.83106176, -1.38427531,  1.32761142, -0.26136258,
        1.4194838 , -0.15176317,  0.82721452, -0.23567583,  0.47640061,
        0.71736692,  1.19101836,  1.13530361,  1.0339734 , -0.70636787])

In [36]:
np.mean(arr)

0.6978755703631214

**15. Create a 2d array with 1 on the border and 0 inside**

In [37]:
two_d = np.ones((5, 5))
two_d[1:-1,1:-1] = 0

two_d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

**16. How to add a border (filled with 0's) around an existing array?**

In [51]:
arr = np.zeros((4, 4))
arr = np.pad(arr, pad_width = 1, mode = 'constant', constant_values = 1)
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

**17. What is the result of the following expression?**

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

In [52]:
0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

False

**18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [54]:
arr = np.diag([1, 2, 3, 4], -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

**19. Create a 8x8 matrix and fill it with a checkerboard pattern**

In [69]:
### Not done

arr = np.zeros((8,8))
arr = np.array[1::1] = np.ones(arr)


TypeError: 'function' object is not subscriptable

**20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?**

In [74]:
### Not done

arr = np.random.rand(6, 7, 8)
np.indices(arr)

TypeError: only integer scalar arrays can be converted to a scalar index

**21. Create a checkerboard 8x8 matrix using the tile function**

In [ ]:
### Come back to when 19. Done

**22. Normalize a 5x5 random matrix**

In [77]:
### Found formula for normalizing numbers, but dont know what it means to normalize a number

arr = np.random.rand(5, 5)
norm = np.linalg.norm(arr)
normal_array = arr/norm
normal_array

array([[0.14187422, 0.22413413, 0.33060203, 0.0924454 , 0.38176451],
       [0.04316403, 0.15411212, 0.25636359, 0.14949888, 0.27108602],
       [0.04660768, 0.09284883, 0.02658683, 0.12377634, 0.14563258],
       [0.32461168, 0.07391381, 0.22439613, 0.09300684, 0.0426736 ],
       [0.17854146, 0.07963184, 0.30113844, 0.19839228, 0.30153201]])